import type { IndustryGuide } from "@/content/industries/types";

export const cybersecurityServicesGuide: IndustryGuide = {
  slug: "cybersecurity-services",
  industryId: "cybersecurity-services",
  name: "Cybersecurity Services",
  metaDescription: "Learn how cybersecurity and MSSP businesses are valued, what buyers diligence, and how to prepare one for a sale.",
  intro: "Cybersecurity services businesses — MSSPs, SOC operators, and compliance-focused security practices — are valued at a premium over general managed IT because security work creates deeper client dependency and stickier, harder-to-replace switching costs. Buyers still diligence the same fundamentals as an MSP, but weight security-specific factors like SOC coverage, incident history, and compliance-driven recurring revenue more heavily.",
  valuationParagraphs: [
    "A buyer will normalize EBITDA and then look beneath it at how much revenue is contracted security monitoring or compliance work (SOC-as-a-service, managed detection and response, virtual CISO, compliance-readiness retainers) versus project-based assessments, penetration testing, or incident response engagements with less predictable timing.",
    "OwnerGauge applies a reviewed cybersecurity-services-specific multiple range to the assessment, informed by public 2025-2026 benchmark data — specialized security services trade at a documented premium over traditional managed IT services, driven by compliance mandates like CMMC pushing more security spend into recurring, contracted revenue.",
  ],
  influenceFactors: ["Contracted security-monitoring and compliance revenue versus project/assessment work", "Client retention and switching costs tied to SOC and compliance ownership", "Incident-response history and any past breach or liability exposure", "Certifications and frameworks supported (SOC 2, CMMC, HIPAA, PCI)", "Analyst and engineer retention, especially SOC/tier-2-3 talent"],
  revenueQuality: ["Contracted MDR/SOC and compliance-retainer revenue is the highest-quality base — it behaves like MRR and buyers weight it accordingly.", "Penetration testing, assessments, and incident-response engagements are valuable but project-based and lumpy; they shouldn't be blended with recurring monitoring revenue.", "Compliance-driven engagements (CMMC readiness, HIPAA, PCI) can be highly recurring if tied to audit cycles, but depend on the regulatory requirement staying in force."],
  ownerDependency: ["Founders in this category are often the most senior technical resource — the person clients actually want responding to a real incident — which is a harder dependency to unwind than in general IT services.", "A buyer tests whether SOC operations, incident response, and client-facing security leadership can run without the founder personally engaged."],
  managementWorkforce: ["Security talent is scarcer and more expensive than general IT talent, and SOC coverage (24/7 monitoring) requires real staffing depth, not just tooling.", "Buyers look for documented escalation procedures, analyst tenure, and whether critical detection/response knowledge is written down or lives in one or two people's heads."],
  growthDrivers: ["Shift the revenue mix toward contracted monitoring and compliance retainers", "Build documented SOC processes and escalation procedures independent of any one analyst", "Pursue compliance frameworks (CMMC, SOC 2) that convert one-time projects into recurring audit-cycle revenue", "Diversify beyond founder-led incident response and business development"],
  buyerConsiderations: ["Client concentration and vertical exposure (especially regulated industries)", "History of security incidents, breaches, or E&O claims", "Analyst depth and SOC coverage model (in-house versus outsourced/white-label)", "Quality and assignability of contracts, especially compliance-retainer agreements"],
  transactionRisks: ["The founder is the only senior incident-response resource", "An unresolved or undisclosed past security incident surfaces in diligence", "SOC coverage relies on a thin bench or white-labeled third party without documented SLAs", "Compliance-driven revenue depends on a regulation or contract mandate that could change"],
  preparationTips: ["Separate and report contracted monitoring/compliance revenue from project work", "Document SOC processes, escalation paths, and incident-response playbooks", "Disclose and remediate any past security incidents before going to market", "Build client-facing security leadership beyond the founder"],
  assessmentCta: "Estimate Your Cybersecurity Services Business Value & Deal Readiness",
};
