import type { IndustryGuide } from "@/content/industries/types";

export const industrialEnvironmentalServicesGuide: IndustryGuide = {
  slug: "industrial-environmental-services",
  industryId: "industrial-environmental-services",
  name: "Industrial & Environmental Services",
  metaDescription: "Learn how industrial and environmental services companies are valued and how to prepare one for a sale.",
  intro: "Industrial and environmental services companies — hazardous waste handling, industrial cleaning, remediation, and regulated-facility maintenance — are valued on the strength of their compliance infrastructure as much as their operating margins. A buyer is underwriting both the business and its exposure to environmental and safety liability, so licensing, permitting, and safety record carry unusual weight.",
  valuationParagraphs: [
    "Owner-operated environmental services companies are typically assessed on SDE, while multi-crew or multi-site operators are more naturally evaluated on normalized EBITDA. A buyer separates recurring maintenance and compliance work (tank testing, industrial cleaning contracts, waste-stream management) from one-time remediation or emergency-response projects, and reviews safety metrics (TRIR, EMR) and permit history closely.",
    "OwnerGauge applies a reviewed industrial-environmental-services-specific multiple range to the assessment, informed by public 2025-2026 benchmark data — regulatory-compliance-driven, recurring environmental work commands a premium over general industrial services, provided the safety and permitting record supports it.",
  ],
  influenceFactors: ["Recurring compliance and maintenance contracts versus one-time remediation or emergency response", "Safety record — TRIR, EMR, and history of incidents or citations", "Permit and license coverage across every jurisdiction and waste stream served", "Specialized equipment (vacuum trucks, remediation systems) age and utilization", "Customer concentration among industrial or municipal accounts"],
  revenueQuality: ["Scheduled compliance work — tank testing, industrial cleaning turnarounds, waste-stream management — recurs predictably with regulatory cycles and customer facility schedules.", "Emergency-response and remediation project revenue can be highly profitable but is unpredictable and shouldn't be blended with recurring contract revenue in reporting.", "Long-term service agreements with industrial or municipal customers are worth more than spot work, especially where the company holds specialized permits competitors lack."],
  ownerDependency: ["The owner often holds key permits, regulatory relationships, and safety-program oversight personally, and may be the one who responds to major emergency-response calls.", "A buyer tests whether permits and licenses transfer cleanly and whether safety and compliance leadership sits with someone besides the owner."],
  managementWorkforce: ["Safety training, certification, and equipment-operator experience are constraints on growth, and a poor safety record can disqualify the company from bidding on industrial accounts.", "Buyers look for a documented safety program, incident history, and operations leadership that isn't solely the owner."],
  growthDrivers: ["Grow recurring compliance-contract revenue relative to one-time remediation work", "Improve and document the safety program to open larger industrial accounts", "Diversify permits and waste-stream capabilities to reduce customer concentration", "Build operations and safety leadership beneath the owner"],
  buyerConsiderations: ["Safety record (TRIR, EMR) and any history of citations or incidents", "Permit and license coverage across jurisdictions and waste streams", "Customer concentration among industrial or municipal accounts", "Environmental liability exposure, including any legacy sites or claims"],
  transactionRisks: ["Safety record or incident history would concern a larger industrial customer or insurer", "Permits or licenses are not transferable, or lapse in certain jurisdictions", "A small number of industrial accounts drive most revenue", "Undisclosed environmental liability from past remediation or waste-handling work"],
  preparationTips: ["Document safety metrics, training records, and incident history", "Confirm permit and license status and transferability across every jurisdiction", "Diversify customer concentration where a few accounts dominate revenue", "Disclose and resolve any environmental liability exposure before diligence"],
  assessmentCta: "Estimate Your Industrial & Environmental Services Business Value & Deal Readiness",
};
