import type { IndustryGuide } from "@/content/industries/types";

export const physicianPracticesGuide: IndustryGuide = {
  slug: "physician-practices",
  industryId: "physician-practices",
  name: "Specialty Medical / Physician Practices",
  metaDescription: "Learn how specialty medical and physician practices are valued, what buyers diligence, and how to prepare one for a sale.",
  intro: "Specialty physician practice value varies enormously by specialty and payer mix — a procedure-heavy specialty with strong commercial reimbursement and ancillary revenue is priced very differently than a cognitive, Medicare-heavy specialty, even at similar revenue. Buyers also navigate corporate-practice-of-medicine restrictions that shape how the deal itself gets structured.",
  valuationParagraphs: [
    "Smaller, single-physician practices are commonly assessed on SDE, while multi-provider practices with a management layer are more naturally evaluated on normalized EBITDA. A buyer reviews payer mix and reimbursement trends, ancillary revenue (in-office imaging, labs, or procedure suites), provider recruiting and non-compete coverage, and how the transaction structure accommodates corporate-practice-of-medicine rules in the practice's state.",
    "OwnerGauge applies a reviewed physician-practice-specific multiple range to the assessment, informed by public 2025-2026 benchmark data — payer mix and specialty carry an outsized effect on where a practice lands, with commercial-payer concentration and procedure-based specialties generally supporting stronger multiples than Medicare-heavy, cognitive specialties.",
  ],
  influenceFactors: ["Payer mix and commercial-versus-Medicare/Medicaid reimbursement rates", "Specialty-specific procedure mix and ancillary revenue (imaging, labs, in-office procedures)", "Provider count and production versus dependence on the owner-physician", "Provider recruiting, retention, and non-compete coverage", "Value-based-care and risk-contract participation"],
  revenueQuality: ["Ancillary services — in-office imaging, labs, or procedure suites — can meaningfully lift margin, but depend on equipment, staffing, and payer coverage to sustain.", "A diversified payer mix with strong commercial representation is worth more than a Medicare/Medicaid-heavy book, given the reimbursement-rate gap between them.", "Production spread across multiple providers is worth more than revenue concentrated in the founding physician, both for continuity and for growth headroom."],
  ownerDependency: ["The founding physician is often the highest-producing provider and the one with the deepest referral relationships.", "A buyer tests whether associate providers can sustain patient volume and referral relationships independent of the founder, and whether corporate-practice-of-medicine rules require a friendly-PC or MSO structure to close the deal."],
  managementWorkforce: ["Provider recruiting is competitive by specialty, and non-compete and restrictive-covenant terms materially affect how much risk a buyer takes on provider departure post-close.", "Buyers look for a practice administrator, documented credentialing and payer-enrollment processes, and clinical leadership beyond the founder."],
  growthDrivers: ["Recruit additional providers to reduce founder-dependent production", "Diversify payer mix and grow commercial-payer representation", "Expand ancillary services where clinically and financially appropriate", "Formalize provider non-compete and restrictive-covenant terms"],
  buyerConsiderations: ["Payer mix and specialty-specific reimbursement trends", "Provider production, recruiting pipeline, and non-compete coverage", "Ancillary revenue durability and required equipment/staffing", "Corporate-practice-of-medicine structure required for the deal"],
  transactionRisks: ["Production is concentrated in the founding physician with a thin associate bench", "Payer mix is heavily weighted toward lower-reimbursing government programs", "Provider agreements lack enforceable non-compete or restrictive-covenant terms", "Corporate-practice-of-medicine rules in the practice's state complicate deal structure"],
  preparationTips: ["Build associate-provider production and reduce founder dependence", "Document payer mix, reimbursement trends, and ancillary-service economics", "Formalize provider recruiting, non-compete, and retention terms", "Confirm the transaction structure required under the state's corporate-practice-of-medicine rules"],
  assessmentCta: "Estimate Your Physician Practice Value & Deal Readiness",
};
