import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle, Compass, Info, SealCheck, Warning } from "@phosphor-icons/react/dist/ssr";
import { sampleHumanReview } from "@/lib/human-review";

export const metadata: Metadata = {
  title: "Standard Human-Review Trip Fit Report",
  description: "Explore Vafaro's standard human-review format with a defined scope, traveler profile, friction map, evidence register, corrections, and unresolved unknowns.",
  alternates: { canonical: "/report" },
};

export default function ReportPage() {
  const review = sampleHumanReview;
  return <main className="report-page">
    <header className="nav shell"><Link className="brand" href="/"><span className="brand-mark"><Compass size={20} weight="fill" /></span>vafaro</Link><Link className="back-link" href="/"><ArrowLeft size={16} /> Back home</Link></header>
    <section className="report-head shell"><div><p className="section-kicker">FAMILY TRIP REVIEW · ILLUSTRATIVE SAMPLE</p><h1>Rome with<br />the family</h1><p>October 12–20 · 6 travelers · Rome & Florence</p></div><div className="report-score"><span>72</span><small>PLANNING<br />SIGNAL</small></div></section>
    <div className="report-meta shell"><span><SealCheck size={18} weight="fill" /> Standard human-review template</span><span>{review.reviewId} · illustrative data · not a customer report</span></div>
    <section className="report-body shell">
      <aside><p>REVIEW RECORD</p><a href="#scope">Scope and profile</a><a href="#summary">Planning summary</a><a href="#friction-map">Friction map</a><a href="#findings">Key findings</a><a href="#evidence">Evidence register</a><a href="#corrections">Corrected plan</a><a href="#unknowns">Unknowns</a></aside>
      <div className="report-content">
        <section className="report-notice"><Info size={21} weight="fill" /><p><strong>Illustrative planning report—not a certification.</strong> Scores summarize planning signals, not safety, medical suitability, or guaranteed accessibility. Important details require current confirmation.</p></section>
        <section id="scope"><p className="section-kicker">AGREED REVIEW SCOPE</p><h2>The reviewer checks only the questions that can change the decision.</h2><div className="review-scope-grid"><div><strong>IN SCOPE</strong><ul>{review.scope.map(item => <li key={item}>{item}</li>)}</ul></div><div><strong>TRAVELER PROFILE USED</strong><ul>{review.travelerProfile.map(item => <li key={item}>{item}</li>)}</ul></div></div></section>
        <section id="summary"><p className="section-kicker">PLANNING SUMMARY</p><h2>A promising trip hiding two difficult days.</h2><p className="lead">{review.summary}</p><div className="fit-bars"><div><span>LODGING SIGNAL</span><i><b style={{width:"82%"}} /></i><strong>82</strong></div><div><span>DAILY PACE</span><i><b style={{width:"58%"}} /></i><strong>58</strong></div><div><span>ACCESS CONFIDENCE</span><i><b style={{width:"44%"}} /></i><strong>44</strong></div><div><span>TRANSITIONS</span><i><b style={{width:"64%"}} /></i><strong>64</strong></div></div></section>
        <section id="friction-map"><p className="section-kicker">DAY-BY-DAY FRICTION MAP</p><h2>Where effort accumulates.</h2><div className="friction-map-table">{review.frictionMap.map(row => <article key={row.segment}><span className={`load load-${row.load.toLowerCase()}`}>{row.load}</span><div><h3>{row.segment}</h3><p>{row.why}</p><strong>Correction</strong><p>{row.correction}</p></div></article>)}</div></section>
        <section id="findings"><p className="section-kicker">THE THREE THINGS TO KNOW</p><article className="report-finding high"><span className="finding-icon"><Warning size={22} weight="fill" /></span><div><p>HIGH FRICTION · DAY 2</p><h3>5.2 estimated walking miles after an overnight flight</h3><span>The current plan combines the Colosseum, Roman Forum, and an evening food tour. The Forum route may include uneven surfaces and limited seating.</span><div className="recommendation"><strong>VAFARO SUGGESTS</strong>Move the food tour to Day 4 and keep the arrival evening unstructured.</div><div className="source-badge">● PLANNING ESTIMATE</div></div></article><article className="report-finding medium"><span className="finding-icon"><Info size={22} weight="fill" /></span><div><p>NEEDS A CHECK · DAY 5</p><h3>18 minutes may not be enough for your Florence connection</h3><span>A platform change, stairs, crowds, or luggage could make this transfer unrealistic for the group.</span><div className="source-badge official">● OFFICIAL SOURCE NEEDED</div></div></article><article className="report-finding positive"><span className="finding-icon"><CheckCircle size={22} weight="fill" /></span><div><p>PROFILE MATCH · LODGING</p><h3>The central Rome location could reduce daily friction</h3><span>The address appears close to several planned activities, but the entrance, lift coverage, room route, and taxi access are not yet verified.</span><div className="source-badge verified-source">● BASED ON FAMILY PROFILE</div></div></article></section>
        <section id="evidence"><p className="section-kicker">EVIDENCE REGISTER</p><h2>Every material claim carries a source, date, and status.</h2><div className="evidence-table" role="table"><div className="evidence-row evidence-head" role="row"><span>Claim</span><span>Source</span><span>Status</span></div>{review.evidence.map(item => <div className="evidence-row" role="row" key={item.claim}><span><strong>{item.claim}</strong><small>{item.notes}</small></span><span>{item.source}<small>{item.checkedOn}</small></span><span><b className={`evidence-status status-${item.status.toLowerCase()}`}>{item.status}</b></span></div>)}</div></section>
        <section id="corrections"><p className="section-kicker">CORRECTED PLAN</p><h2>A useful review ends with a workable alternative.</h2><ol className="corrected-plan">{review.correctedPlan.map(item => <li key={item}>{item}</li>)}</ol></section>
        <section className="report-unknowns" id="unknowns"><p className="section-kicker">UNRESOLVED AT DELIVERY</p><h2>Three facts could still change the recommendation.</h2><ul>{review.unresolved.map(item => <li key={item}>{item}</li>)}</ul><p className="review-signoff"><strong>Reviewer record:</strong> {review.reviewer} · {review.reviewedOn}. Reconfirm time-sensitive facts directly before booking.</p></section>
        <section className="human-callout"><SealCheck size={30} weight="fill" /><div><p>FOUNDING-FAMILY REVIEW</p><h2>Want a person to investigate the priority unknowns?</h2><span>Proposed founding price: $119. Exact research scope and price are confirmed before payment.</span></div><Link className="button" href="/check">Join the founding list <ArrowRight size={17} /></Link></section>
      </div>
    </section>
  </main>;
}
