import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle, Compass, Info, SealCheck, Warning } from "@phosphor-icons/react/dist/ssr";

export default function ReportPage() {
  return <main className="report-page">
    <header className="nav shell"><Link className="brand" href="/"><span className="brand-mark"><Compass size={20} weight="fill" /></span>vafaro</Link><Link className="back-link" href="/"><ArrowLeft size={16} /> Back home</Link></header>
    <section className="report-head shell"><div><p className="section-kicker">TRIP FIT REPORT · SAMPLE</p><h1>Rome with<br />the family</h1><p>October 12–20 · 6 travelers · Rome & Florence</p></div><div className="report-score"><span>72</span><small>TRIP FIT<br />OUT OF 100</small></div></section>
    <div className="report-meta shell"><span><SealCheck size={18} weight="fill" /> Human reviewed by Maria C.</span><span>Updated August 13, 2026</span></div>
    <section className="report-body shell">
      <aside><p>OVERVIEW</p><a href="#summary">Fit summary</a><a href="#findings">Key findings</a><a href="#days">Day-by-day</a><a href="#sources">Sources</a></aside>
      <div className="report-content">
        <section id="summary"><p className="section-kicker">FIT SUMMARY</p><h2>A good trip hiding two difficult days.</h2><p className="lead">Your hotels and overall route suit the group well. The main concern is front-loading the most physically demanding activities immediately after an overnight flight.</p><div className="fit-bars"><div><span>LODGING FIT</span><i><b style={{width:"91%"}} /></i><strong>91</strong></div><div><span>DAILY PACE</span><i><b style={{width:"58%"}} /></i><strong>58</strong></div><div><span>ACCESS & MOBILITY</span><i><b style={{width:"76%"}} /></i><strong>76</strong></div><div><span>TRANSITIONS</span><i><b style={{width:"64%"}} /></i><strong>64</strong></div></div></section>
        <section id="findings"><p className="section-kicker">THE THREE THINGS TO KNOW</p><article className="report-finding high"><span className="finding-icon"><Warning size={22} weight="fill" /></span><div><p>HIGH FRICTION · DAY 2</p><h3>5.2 estimated walking miles after an overnight flight</h3><span>The current plan combines the Colosseum, Roman Forum, and an evening food tour. The Forum has uneven surfaces and limited seating.</span><div className="recommendation"><strong>VAFARO SUGGESTS</strong>Move the food tour to Day 4 and keep the arrival evening unstructured.</div></div></article><article className="report-finding medium"><span className="finding-icon"><Info size={22} weight="fill" /></span><div><p>NEEDS A CHECK · DAY 5</p><h3>18 minutes may not be enough for your Florence connection</h3><span>The platform is assigned shortly before departure and could require stairs or a busy underpass with luggage.</span><div className="source-badge official">● CONFIRMED BY OFFICIAL SOURCE</div></div></article><article className="report-finding positive"><span className="finding-icon"><CheckCircle size={22} weight="fill" /></span><div><p>STRONG FIT · LODGING</p><h3>Your Rome hotel is an excellent base for this group</h3><span>The entrance is step-free, the lift reaches all guest floors, and seven key plans are within a 12-minute taxi ride.</span><div className="source-badge verified-source">● VERIFIED DIRECTLY · HOTEL CALLED AUG 12</div></div></article></section>
        <section className="human-callout"><SealCheck size={30} weight="fill" /><div><p>HUMAN REVIEW AVAILABLE</p><h2>Want us to verify the details that matter most?</h2><span>A Vafaro reviewer can call hotels, confirm access, and help rebalance difficult days.</span></div><button className="button">Request a human check <ArrowRight size={17} /></button></section>
      </div>
    </section>
  </main>;
}
